In [ ]:
#def func_gradient(func, theta_sym, values):
#    grad = np.array([diff(L(*theta_sym), i) for i in theta_sym])
#    substitutes = list(zip(theta_sym, values))
#
#    for i, element in enumerate(grad):
#        for j in substitutes:
#            grad[i] = grad[i].subs(*j)
#    return grad  

In [6]:
def L(x,y):
    return x**2*y**2 + y**2

def L_gradient(x,y):
    return np.array([2*x*y**2, 2*x**2 * y + 2*y])


In [7]:
# from Algorithm 1: HMC, page1353
def Leapfrog(theta, r, eps, L, L_gradient):
    r_tilde = r + (eps/2) * L_gradient(*theta)
    theta_tilde = theta + eps * r_tilde
    r_tide = r_tilde + (eps/2) * L_gradient(*theta_tilde)
    return theta_tilde, r_tilde

In [8]:
theta = [0.5,0.4]
r = [0.5, 0.4]
u = 0.5
v = 0.5
Leapfrog(theta, r, u, v, L_gradient)

(array([ 0.77 ,  0.725]), array([ 0.54,  0.65]))

In [17]:
def BuildTree(theta, r, u, v, j, eps):
    if j == 0:
        # base case, take one leapfrog step in the direction v
        theta_prime, r_prime = Leapfrog(theta, r, v*eps, L, L_gradient)
        
        if u <= np.exp(L(*theta_prime) - 0.5 * np.dot(r_prime, r_prime)):
            C_prime = np.append(theta_prime, r_prime)
        else:
            C_prime = np.empty(shape=(0, 0))
        
        s_prime = int(L(*theta_prime) - 0.5 * np.dot(r_prime, r_prime) > np.log(u) - 1000)
        
        return theta_prime, r_prime, theta_prime, r_prime, C_prime, s_prime
    else:
        # recursion, build left and right subtrees
        theta_minus, r_minus, theta_plus, r_plus, C_prime, s_prime = BuildTree(theta, r, u, v, j-1, eps)
        
        if v == -1:
            theta_minus, r_minus, _,_, C_doub_prime, s_doub_prime = BuildTree(theta_minus, r_minus, u, v, j-1, eps)
        else:
            _,_, theta_plus, r_plus, C_doub_prime, s_doub_prime = BuildTree(theta_plus, r_plus, u, v, j-1, eps)
            
        ind_1 = int(np.dot(theta_plus-theta_minus, r_minus) >= 0)
        ind_2 = int(np.dot(theta_plus-theta_minus, r_plus) >= 0)
        s_prime = s_prime * s_doub_prime * ind_1 * ind_2
        C_prime = np.append(C_prime, C_doub_prime)
        
        return theta_minus, r_minus, theta_plus, r_plus, C_prime, s_prime

In [25]:
BuildTree(theta, r, 0.5, 5, 1, 0.5)

(array([ 2.25 ,  4.525]),
 array([ 0.7 ,  1.65]),
 array([ 291.93847656,  180.10507813]),
 array([ 115.87539063,   70.23203125]),
 array([   2.25      ,    4.525     ,    0.7       ,    1.65      ,
         291.93847656,  180.10507813,  115.87539063,   70.23203125]),
 1)

In [ ]:
naive_nuts(theta0, eps, L, M

In [ ]:
one = np.array([1,2])
two = np.array([3,4])
values

In [ ]:
np.append(one,two)

In [ ]:
esto = 2 > 3
1 * esto

In [ ]:
int(esto)

In [ ]:
2 * 3