In [ ]:
import sympy
from sympy import *
from sympy import init_session
init_session()

In [115]:
def func_gradient(func, theta_sym, values):
    grad = np.array([diff(L(*theta_sym), i) for i in theta_sym])
    substitutes = list(zip(theta_sym, values))

    for i, element in enumerate(grad):
        for j in substitutes:
            grad[i] = grad[i].subs(*j)
    return grad  


In [116]:
def L(x,y):
    return x**2 + y**2

theta_sym = [x,y]
values = [2,4]

func_gradient(L, theta_sym, values)

array([4, 8], dtype=object)

In [120]:
# from Algorithm 1: HMC, page1353
def Leapfrog(theta, r, eps, theta_sym):
    r_tilde = r + (eps/2) * func_gradient(L, theta_sym, values = theta)
    theta_tilde = theta + eps * r_tilde
    r_tide = r_tilde + (eps/2) * func_gradient(L, theta_sym, values = theta_tilde)
    return theta_tilde, r_tilde

(array([5.00000000000000, 9.00000000000000], dtype=object),
 array([3.00000000000000, 5.00000000000000], dtype=object))

In [41]:
def BuildTree(theta, r, mu, v, j, eps):